{% set name = "apc" %}
{% set version = "v0.1.1" %}
{% set sha256 = "798cf31b69ceb7e1085e24d860b66bc0f6fd5494af50791d2ccdf91696d3bfc2" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  noarch: generic

source:
  url: https://github.com/ralatsdc/apc/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  # LAST aligner (tested with v548)
  # BWA (tested with v0.7.10)
  # samtools (tested with v1.2)
  run:
    - perl
    - last >=548
    - bwa >=0.7.10
    - samtools >=1.6

test:
  files:
    - "contigs.fa"

  commands:
    - "apc.pl -b actual contigs.fa && diff actual.1.fa expected.1.fa"

about:
  home: https://github.com/ralatsdc/apc
  license: None
  license_file: LICENSE
  summary: (a) (p)erfect (c)ircle?
